/*
 * module.c
 *
 * This file is part of the TULIP4041 project.
 * Copyright (C) 2024 Meindert Kuipers
 * 
 * This file contains the higher level emulation of peripherals:
 *  - IR printing
 *  - HP-IL communication and PILBox emulation
 *  - IO definitions and initialization
 *
 * This is free software: you are free to change and redistribute it.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * 
 * USE AT YOUR OWN RISK
 *
 */

#include "module.h"

// forthe BETA version this file contains the ROM images for the HP-IL ROM and the HP-IL Printer

const char __in_flash() *mnemonics[] = 
// const char *mnemonics[] = 
// list of HP41 mnemonics, JDA style
// forced in FLASH to maximize SRAM
{
"NOP",          "GO/XQ",        "A=0 @R",       "JNC +0",       "CLRF 3",       "GO/XQ",        "A=0 S&X",      "JC 0",     
"SETF 3",       "GO/XQ",        "A=0 R<-",      "JNC +1",       "?FSET 3",      "GO/XQ",        "A=0 ALL",      "JC 1",         
"LD@R 0",       "GO/XQ",        "A=0 P-Q",      "JNC +2",       "?R= 3",        "GO/XQ ",       "A=0 XS",       "JC 2",
"UNUSED ",      "GO/XQ ",       "A=0 M",        "JNC +3",       "R= 3",         "GO/XQ ",       "A=0 MS",       "JC 3",
"XQ>GO ",       "GO/XQ ",       "B=0 @R",       "JNC +4",       "SELP 0",       "GO/XQ ",       "B=0 S&X",      "JC 4",
"WRIT 0(T)",    "GO/XQ ",       "B=0 R<-",      "JNC +5",       "?FI 3",        "GO/XQ ",       "B=0 ALL",      "JC 5",
"ROMBLK ",      "GO/XQ ",       "B=0 P-Q",      "JNC +6",       "UNUSED ",      "GO/XQ ",       "B=0 XS",       "JC 6",
"READ 0(T)",    "GO/XQ ",       "B=0 M",        "JNC +7",       "RCR 3",        "GO/XQ ",       "B=0 MS",       "JC 7",
"WROM ",        "GO/XQ ",       "C=0 @R",       "JNC +8",       "CLRF 4",       "GO/XQ ",       "C=0 S&X",      "JC 8",
"SETF 4",       "GO/XQ ",       "C=0 R<-",      "JNC +9",       "?FSET 4",      "GO/XQ ",       "C=0 ALL",      "JC 9",
"LD@R 1",       "GO/XQ ",       "C=0 P-Q",      "JNC +10",      "?R= 4",        "GO/XQ ",       "C=0 XS",       "JC 10",
"G=C ",         "GO/XQ ",       "C=0 M",        "JNC +11",      "R= 4",         "GO/XQ ",       "C=0 MS",       "JC 11",        
"POWOFF ",      "GO/XQ ",       "A<>B @R",      "JNC +12",      "SELP 1",       "GO/XQ ",       "A<>B S&X",     "JC 12",
"WRIT 1(Z)",    "GO/XQ ",       "A<>B R<-",     "JNC +13",      "?FI 4",        "GO/XQ ",       "A<>B ALL",     "JC 13",
"N=C ",         "GO/XQ ",       "A<>B P-Q",     "JNC +14",      "UNUSED ",      "GO/XQ ",       "A<>B XS",      "JC 14",
"READ 1(Z)",    "GO/XQ ",       "A<>B M",       "JNC +15",      "RCR 4",        "GO/XQ ",       "A<>B MS",      "JC 15",
"UNUSED ",      "GO/XQ ",       "B=A @R",       "JNC +16",      "CLRF 5",       "GO/XQ ",       "B=A S&X",      "JC 16",
"SETF 5",       "GO/XQ ",       "B=A R<-",      "JNC +17",      "?FSET 5",      "GO/XQ ",       "B=A ALL",      "JC 17",
"LD@R 2",       "GO/XQ ",       "B=A P-Q",      "JNC +18",      "?R= 5",        "GO/XQ ",       "B=A XS",       "JC 18",
"C=G ",         "GO/XQ ",       "B=A M",        "JNC +19",      "R= 5",         "GO/XQ ",       "B=A MS",       "JC 19",
"SLCTP ",       "GO/XQ ",       "A<>C @R",      "JNC +20",      "SELP 2",       "GO/XQ ",       "A<>C S&X",     "JC 20",
"WRIT 2(Y)",    "GO/XQ ",       "A<>C R<-",     "JNC +21",      "?FI 5 ?EDAV",  "GO/XQ ",       "A<>C ALL",     "JC 21",
"C=N ",         "GO/XQ ",       "A<>C P-Q",     "JNC +22",      "UNUSED ",      "GO/XQ ",       "A<>C XS",      "JC 22",
"READ 2(Y)",    "GO/XQ ",       "A<>C M",       "JNC +23",      "RCR 5",        "GO/XQ ",       "A<>C MS",      "JC 23",
"UNUSED ",      "GO/XQ ",       "C=B @R",       "JNC +24",      "CLRF 10",      "GO/XQ ",       "C=B S&X",      "JC 24",
"SETF 10",      "GO/XQ ",       "C=B R<-",      "JNC +25",      "?FSET 10",     "GO/XQ ",       "C=B ALL",      "JC 25",
"LD@R 3",       "GO/XQ ",       "C=B P-Q",      "JNC +26",      "?R= 10",       "GO/XQ ",       "C=B XS",       "JC 26",
"C<>G ",        "GO/XQ ",       "C=B M",        "JNC +27",      "R= 10",        "GO/XQ ",       "C=B MS",       "JC 27",
"SLCTQ ",       "GO/XQ ",       "B<>C @R",      "JNC +28",      "SELP 3",       "GO/XQ ",       "B<>C S&X",     "JC 28",
"WRIT 3(X)",    "GO/XQ ",       "B<>C R<-",     "JNC +29",      "?FI 10 ?ORAV", "GO/XQ ",       "B<>C ALL",     "JC 29",
"C<>N ",        "GO/XQ ",       "B<>C P-Q",     "JNC +30",      "UNUSED ",      "GO/XQ ",       "B<>C XS",      "JC 30",
"READ 3(X)",    "GO/XQ ",       "B<>C M",       "JNC +31",      "RCR 10",       "GO/XQ ",       "B<>C MS",      "JC 31",
"ENBANK1 ",     "GO/XQ ",       "A=C @R",       "JNC +32",      "CLRF 8",       "GO/XQ ",       "A=C S&X",      "JC 32",
"SETF 8",       "GO/XQ ",       "A=C R<-",      "JNC +33",      "?FSET 8",      "GO/XQ ",       "A=C ALL",      "JC 33",
"LD@R 4",       "GO/XQ ",       "A=C P-Q",      "JNC +34",      "?R= 8",        "GO/XQ ",       "A=C XS",       "JC 34",
"UNUSED ",      "GO/XQ ",       "A=C M",        "JNC +35",      "R= 8",         "GO/XQ ",       "A=C MS",       "JC 35",
"?P=Q ",        "GO/XQ ",       "A=A+B @R",     "JNC +36",      "SELP 4",       "GO/XQ ",       "A=A+B S&X",    "JC 36",
"WRIT 4(L)",    "GO/XQ ",       "A=A+B R<-",    "JNC +37",      "?FI 8 ?FRAV",  "GO/XQ ",       "A=A+B ALL",    "JC 37",
"LDI ",         "GO/XQ ",       "A=A+B P-Q",    "JNC +38",      "UNUSED ",      "GO/XQ ",       "A=A+B XS",     "JC 38",
"READ 4(L)",    "GO/XQ ",       "A=A+B M",      "JNC +39",      "RCR 8",        "GO/XQ ",       "A=A+B MS",     "JC 39",
"ENBANK3 ",     "GO/XQ ",       "A=A+C @R",     "JNC +40",      "CLRF 6",       "GO/XQ ",       "A=A+C S&X",    "JC 40",
"SETF 6",       "GO/XQ ",       "A=A+C R<-",    "JNC +41",      "?FSET 6",      "GO/XQ ",       "A=A+C ALL",    "JC 41",
"LD@R 5",       "GO/XQ ",       "A=A+C P-Q",    "JNC +42",      "?R= 6",        "GO/XQ ",       "A=A+C XS",     "JC 42",
"M=C ",         "GO/XQ ",       "A=A+C M",      "JNC +43",      "R= 6",         "GO/XQ ",       "A=A+C MS",     "JC 43",
"?LOWBAT ",     "GO/XQ ",       "A=A+1 @R",     "JNC +44",      "SELP 5",       "GO/XQ ",       "A=A+1 S&X",    "JC 44",
"WRIT 5(M)",    "GO/XQ ",       "A=A+1 R<-",    "JNC +45",      "?FI 6 ?IFCR",  "GO/XQ ",       "A=A+1 ALL",    "JC 45",
"PUSHADR ",
"GO/XQ ",
"A=A+1 P-Q",
"JNC +46",
"UNUSED ",
"GO/XQ ",
"A=A+1 XS",
"JC 46",
"READ 5(M)",
"GO/XQ ",
"A=A+1 M",
"JNC +47",
"RCR 6",
"GO/XQ ",
"A=A+1 MS",
"JC 47",
"ENBANK2 ",
"GO/XQ ",
"A=A-B @R",
"JNC +48",
"CLRF 11",
"GO/XQ ",
"A=A-B S&X",
"JC 48",
"SETF 11",
"GO/XQ ",
"A=A-B R<-",
"JNC +49",
"?FSET 11",
"GO/XQ ",
"A=A-B ALL",
"JC 49",
"LD@R 6",
"GO/XQ ",
"A=A-B P-Q",
"JNC +50",
"?R= 11",
"GO/XQ ",
"A=A-B XS",
"JC 50",
"C=M ",
"GO/XQ ",
"A=A-B M",
"JNC +51",
"R= 11",
"GO/XQ ",
"A=A-B MS",
"JC 51",
"A=B=C=0 ",
"GO/XQ ",
"A=A-1 @R",
"JNC +52",
"SELP 6",
"GO/XQ ",
"A=A-1 S&X",
"JC 52",
"WRIT 6(N)",
"GO/XQ ",
"A=A-1 R<-",
"JNC +53",
"?FI 11 ?TFAIL",
"GO/XQ ",
"A=A-1 ALL",
"JC 53",
"POPADR ",
"GO/XQ ",
"A=A-1 P-Q",
"JNC +54",
"UNUSED ",
"GO/XQ ",
"A=A-1 XS",
"JC 54",
"READ 6(N)",
"GO/XQ ",
"A=A-1 M",
"JNC +55",
"RCR 11",
"GO/XQ ",
"A=A-1 MS",
"JC 55",
"ENBANK4 ",
"GO/XQ ",
"A=A-C @R",
"JNC +56",
"UNUSED ",
"GO/XQ ",
"A=A-C S&X",
"JC 56",
"UNUSED ",
"GO/XQ ",
"A=A-C R<-",
"JNC +57",
"UNUSED ",
"GO/XQ ",
"A=A-C ALL",
"JC 57",
"LD@R 7",
"GO/XQ ",
"A=A-C P-Q",
"JNC +58",
"UNUSED ",
"GO/XQ ",
"A=A-C XS",
"JC 58",
"C<>M ",
"GO/XQ ",
"A=A-C M",
"JNC +59",
"UNUSED ",
"GO/XQ ",
"A=A-C MS",
"JC 59",
"GOTOADR ",
"GO/XQ ",
"C=C+C @R",
"JNC +60",
"SELP 7",
"GO/XQ ",
"C=C+C S&X",
"JC 60",
"WRIT 7(O)",
"GO/XQ ",
"C=C+C R<-",
"JNC +61",
"UNUSED ",
"GO/XQ ",
"C=C+C ALL",
"JC 61",
"WPTOG ",
"GO/XQ ",
"C=C+C P-Q",
"JNC +62",
"UNUSED ",
"GO/XQ ",
"C=C+C XS",
"JC 62",
"READ 7(O)",
"GO/XQ ",
"C=C+C M",
"JNC +63",
"WCMD ",
"GO/XQ ",
"C=C+C MS",
"JC 63",
"HPIL=C 0",
"GO/XQ ",
"C=C+A @R",
"JNC -64",
"CLRF 2",
"GO/XQ ",
"C=C+A S&X",
"JC -64",
"SETF 2",
"GO/XQ ",
"C=C+A R<-",
"JNC -63",
"?FSET 2",
"GO/XQ ",
"C=C+A ALL",
"JC -63",
"LD@R 8",
"GO/XQ ",
"C=C+A P-Q",
"JNC -62",
"?R= 2",
"GO/XQ ",
"C=C+A XS",
"JC -62",
"UNUSED ",
"GO/XQ ",
"C=C+A M",
"JNC -61",
"R= 2",
"GO/XQ ",
"C=C+A MS",
"JC -61",
"C=KEY ",
"GO/XQ ",
"C=C+1 @R",
"JNC -60",
"SELP 8",
"GO/XQ ",
"C=C+1 S&X",
"JC -60",
"WRIT 8(P)",
"GO/XQ ",
"C=C+1 R<-",
"JNC -59",
"?FI 2 ?WNDB",
"GO/XQ ",
"C=C+1 ALL",
"JC -59",
"GTOKEY ",
"GO/XQ ",
"C=C+1 P-Q",
"JNC -58",
"UNUSED ",
"GO/XQ ",
"C=C+1 XS",
"JC -58",
"READ 8(P)",
"GO/XQ ",
"C=C+1 M",
"JNC -57",
"RCR 2",
"GO/XQ ",
"C=C+1 MS",
"JC -57",
"HPIL=C 1",
"GO/XQ ",
"C=A-C @R",
"JNC -56",
"CLRF 9",
"GO/XQ ",
"C=A-C S&X",
"JC -56",
"SETF 9",
"GO/XQ ",
"C=A-C R<-",
"JNC -55",
"?FSET 9",
"GO/XQ ",
"C=A-C ALL",
"JC -55",
"LD@R 9",
"GO/XQ ",
"C=A-C P-Q",
"JNC -54",
"?R= 9",
"GO/XQ ",
"C=A-C XS",
"JC -54",
"T=ST ",
"GO/XQ ",
"C=A-C M",
"JNC -53",
"R= 9",
"GO/XQ ",
"C=A-C MS",
"JC -53",
"SETHEX ",
"GO/XQ ",
"C=C-1 @R",
"JNC -52",
"SELP 9",
"GO/XQ ",
"C=C-1 S&X",
"JC -52",
"WRIT 9(Q)",
"GO/XQ ",
"C=C-1 R<-",
"JNC -51",
"?FI 9 ?FRNS",
"GO/XQ ",
"C=C-1 ALL",
"JC -51",
"RAMSLCT ",
"GO/XQ ",
"C=C-1 P-Q",
"JNC -50",
"UNUSED ",
"GO/XQ ",
"C=C-1 XS",
"JC -50",
"READ 9(Q)",
"GO/XQ ",
"C=C-1 M",
"JNC -49",
"RCR 9",
"GO/XQ ",
"C=C-1 MS",
"JC -49",
"HPIL=C 2",
"GO/XQ ",
"C=0-C @R",
"JNC -48",
"CLRF 7",
"GO/XQ ",
"C=0-C S&X",
"JC -48",
"SETF 7",
"GO/XQ ",
"C=0-C R<-",
"JNC -47",
"?FSET 7",
"GO/XQ ",
"C=0-C ALL",
"JC -47",
"LD@R A",
"GO/XQ ",
"C=0-C P-Q",
"JNC -46",
"?R= 7",
"GO/XQ ",
"C=0-C XS",
"JC -46",
"ST=T ",
"GO/XQ ",
"C=0-C M",
"JNC -45",
"R= 7",
"GO/XQ ",
"C=0-C MS",
"JC -45",
"SETDEC ",
"GO/XQ ",
"C=-C-1 @R",
"JNC -44",
"SELP A",
"GO/XQ ",
"C=-C-1 S&X",
"JC -44",
"WRIT 10(+)",
"GO/XQ ",
"C=-C-1 R<-",
"JNC -43",
"?FI 7 ?SRQR",
"GO/XQ ",
"C=-C-1 ALL",
"JC -43",
"UNUSED ",
"GO/XQ ",
"C=-C-1 P-Q",
"JNC -42",
"UNUSED ",
"GO/XQ ",
"C=-C-1 XS",
"JC -42",
"READ 10(+)",
"GO/XQ ",
"C=-C-1 M",
"JNC -41",
"RCR 7",
"GO/XQ ",
"C=-C-1 MS",
"JC -41",
"HPIL=C 3",
"GO/XQ ",
"?B#0 @R",
"JNC -40",
"CLRF 13",
"GO/XQ ",
"?B#0 S&X",
"JC -40",
"SETF 13",
"GO/XQ ",
"?B#0 R<-",
"JNC -39",
"?FSET 13",
"GO/XQ ",
"?B#0 ALL",
"JC -39",
"LD@R B",
"GO/XQ ",
"?B#0 P-Q",
"JNC -38",
"?R= 13",
"GO/XQ ",
"?B#0 XS",
"JC -38",
"ST<>T ",
"GO/XQ ",
"?B#0 M",
"JNC -37",
"R= 13",
"GO/XQ ",
"?B#0 MS",
"JC -37",
"DSPOFF ",
"GO/XQ ",
"?C#0 @R",
"JNC -36",
"SELP B",
"GO/XQ ",
"?C#0 S&X",
"JC -36",
"WRIT 11(a)",
"GO/XQ ",
"?C#0 R<-",
"JNC -35",
"?FI 13 ?SERV",
"GO/XQ ",
"?C#0 ALL",
"JC -35",
"WRITDAT ",
"GO/XQ ",
"?C#0 P-Q",
"JNC -34",
"UNUSED ",
"GO/XQ ",
"?C#0 XS",
"JC -34",
"READ 11(a)",
"GO/XQ ",
"?C#0 M",
"JNC -33",
"RCR 13",
"GO/XQ ",
"?C#0 MS",
"JC -33",
"HPIL=C 4",
"GO/XQ ",
"?A<C @R",
"JNC -32",
"CLRF 1",
"GO/XQ ",
"?A<C S&X",
"JC -32",
"SETF 1",
"GO/XQ ",
"?A<C R<-",
"JNC -31",
"?FSET 1",
"GO/XQ ",
"?A<C ALL",
"JC -31",
"LD@R C",
"GO/XQ ",
"?A<C P-Q",
"JNC -30",
"?R= 1",
"GO/XQ ",
"?A<C XS",
"JC -30",
"UNUSED ",
"GO/XQ ",
"?A<C M",
"JNC -29",
"R= 1",
"GO/XQ ",
"?A<C MS",
"JC -29",
"DSPTOG ",
"GO/XQ ",
"?A<B @R",
"JNC -28",
"SELP C",
"GO/XQ ",
"?A<B S&X",
"JC -28",
"WRIT 12(b)",
"GO/XQ ",
"?A<B R<-",
"JNC -27",
"?FI 1 ?CRDR",
"GO/XQ ",
"?A<B ALL",
"JC -27",
"FETCH S&X ",
"GO/XQ ",
"?A<B P-Q",
"JNC -26",
"UNUSED ",
"GO/XQ ",
"?A<B XS",
"JC -26",
"READ 12(b)",
"GO/XQ ",
"?A<B M",
"JNC -25",
"RCR 1",
"GO/XQ ",
"?A<B MS",
"JC -25",
"HPIL=C 5",
"GO/XQ ",
"?A#0 @R",
"JNC -24",
"CLRF 12",
"GO/XQ ",
"?A#0 S&X",
"JC -24",
"SETF 12",
"GO/XQ ",
"?A#0 R<-",
"JNC -23",
"?FSET 12",
"GO/XQ ",
"?A#0 ALL",
"JC -23",
"LD@R D",
"GO/XQ ",
"?A#0 P-Q",
"JNC -22",
"?R= 12",
"GO/XQ ",
"?A#0 XS",
"JC -22",
"ST=C ",
"GO/XQ ",
"?A#0 M",
"JNC -21",
"R= 12",
"GO/XQ ",
"?A#0 MS",
"JC -21",
"?C RTN ",
"GO/XQ ",
"?A#C @R",
"JNC -20",
"SELP D",
"GO/XQ ",
"?A#C S&X",
"JC -20",
"WRIT 13(c)",
"GO/XQ ",
"?A#C R<-",
"JNC -19",
"?FI 12 ?ALM",
"GO/XQ ",
"?A#C ALL",
"JC -19",
"C=C O RA ",
"GO/XQ ",
"?A#C P-Q",
"JNC -18",
"UNUSED ",
"GO/XQ ",
"?A#C XS",
"JC -18",
"READ 13(c)",
"GO/XQ ",
"?A#C M",
"JNC -17",
"RCR 12",
"GO/XQ ",
"?A#C MS",
"JC -17",
"HPIL=C 6",
"GO/XQ ",
"RSHFA @R",
"JNC -16",
"CLRF 0",
"GO/XQ ",
"RSHFA S&X",
"JC -16",
"SETF 0",
"GO/XQ ",
"RSHFA R<-",
"JNC -15",
"?FSET 0",
"GO/XQ ",
"RSHFA ALL",
"JC -15",
"LD@R E",
"GO/XQ ",
"RSHFA P-Q",
"JNC -14",
"?R= 0",
"GO/XQ ",
"RSHFA XS",
"JC -14",
"C=ST ",
"GO/XQ ",
"RSHFA M",
"JNC -13",
"R= 0",
"GO/XQ ",
"RSHFA MS",
"JC -13",
"?NC RTN ",
"GO/XQ ",
"RSHFB @R",
"JNC -12",
"SELP E",
"GO/XQ ",
"RSHFB S&X",
"JC -12",
"WRIT 14(d)",
"GO/XQ ",
"RSHFB R<-",
"JNC -11",
"?FI 0 ?PBSY",
"GO/XQ ",
"RSHFB ALL",
"JC -11",
"C=C AND A ",
"GO/XQ ",
"RSHFB P-Q",
"JNC -10",
"UNUSED ",
"GO/XQ ",
"RSHFB XS",
"JC -10",
"READ 14(d)",
"GO/XQ ",
"RSHFB M",
"JNC -9",
"RCR 0",
"GO/XQ ",
"RSHFB MS",
"JC -9",
"HPIL=C 7",
"GO/XQ ",
"RSHFC @R",
"JNC -8",
"ST=0 ",
"GO/XQ ",
"RSHFC S&X",
"JC -8",
"CLRKEY ",
"GO/XQ ",
"RSHFC R<-",
"JNC -7",
"?KEY ",
"GO/XQ ",
"RSHFC ALL",
"JC -7",
"LD@R F",
"GO/XQ ",
"RSHFC P-Q",
"JNC -6",
"R=R-1 ",
"GO/XQ ",
"RSHFC XS",
"JC -6",
"C<>ST ",
"GO/XQ ",
"RSHFC M",
"JNC -5",
"R=R+1 ",
"GO/XQ ",
"RSHFC MS",
"JC -5",
"RTN ",
"GO/XQ ",
"LSHFA @R",
"JNC -4",
"SELP F",
"GO/XQ ",
"LSHFA S&X",
"JC -4",
"WRIT 15(e)",
"GO/XQ ",
"LSHFA R<-",
"JNC -3",
"?FI ",
"GO/XQ ",
"LSHFA ALL",
"JC -3",
"PRPHSLCT ",
"GO/XQ ",
"LSHFA P-Q",
"JNC -2",
"UNUSED ",
"GO/XQ ",
"LSHFA XS",
"JC -2",
"READ 15(e)",
"GO/XQ ",
"LSHFA M",
"JNC -1",
"UNUSED ",
"GO/XQ ",
"LSHFA MS",
"JC -1",
};





// end of file module.c